name: 定时采集

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 在 Ubuntu 上运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        env:
          GOOS: "${{ matrix.os }}"
          GOARCH: "${{ matrix.arch }}"
        run: |
          mkdir ./dist \
          go build -ldflags="-s -w" -o "./dist/${{matrix.cmd}}-${{ matrix.os }}-${{ matrix.arch }}" cmd/${{matrix.cmd}}/main.go

      - name: Create zip file for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          cd ./dist \
          zip -r "${{matrix.cmd}}-${{ matrix.os }}-${{ matrix.arch }}.zip" "${{matrix.cmd}}-${{ matrix.os }}-${{ matrix.arch }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: torrent_tools
          path: ./dist/${{matrix.cmd}}-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: torrent_tools  # 下载构建的 zip 文件

      - name: Create release or pre-release
        id: create_release
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # 如果是标签推送，创建正式版本
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "Creating release for tag $TAG_NAME"
            PRE_RELEASE=false
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            # 如果是分支推送，创建预发布版本
            COMMIT_ID=$(git rev-parse --short HEAD)
            echo "Creating pre-release for commit $COMMIT_ID"
            TAG_NAME="pre-release-${COMMIT_ID}"
            PRE_RELEASE=true
          fi
          
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "PRE_RELEASE=$PRE_RELEASE" >> $GITHUB_ENV

      - name: Upload release assets (zip files)
        uses: softprops/action-gh-release@v2
        with:
          files: "./dist/*.zip"  # 上传所有构建的 zip 文件
          tag_name: ${{env.TAG_NAME}}
          prerelease: ${{env.PRE_RELEASE}}
